version: "3"
services:
  mysql-db:
    image: mysql:8
    container_name: mange_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: mange
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mange

  redis:
    image: redis:latest
    container_name: mange_redis
    networks:
      - mange

  nginx:
    container_name: mange_nginx
    image: nginx:latest
    ports:
      - "8000:80"
    depends_on:
      - laravel-backend
    networks:
      - mange
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - backend_code:/var/www/html/

  laravel-backend:
    container_name: mange_laravel
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - mysql-db
    networks:
      - mange
    env_file:
      - ./backend/.env
    environment:
      - APP_ENV=production
      # - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_DATABASE=mange
      - DB_USERNAME=root
      - DB_PASSWORD=1111
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
    volumes:
      - backend_code:/var/www/html/
    command: sh -c "cp -r /app/. /var/www/html/ && chown -R www-data:www-data /var/www/html/ && php-fpm" # Copy sang shared volume

  laravel-worker:
    container_name: mange_laravel_worker
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - mysql-db
    networks:
      - mange
    env_file:
      - ./backend/.env
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_DATABASE=mange
      - DB_USERNAME=root
      - DB_PASSWORD=1111
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
    volumes:
      - backend_code:/var/www/html/
    restart: always
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3", "--sleep=3"]

  laravel-echo-server:
    container_name: mange_laravel_echo_server
    build:
      dockerfile: Dockerfile.echo_server
      context: "./backend"
    depends_on:
      - mysql-db
      - redis
      - laravel-backend
    networks:
      - mange
    ports:
      - "6001:6001"
    restart: always
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - LARAVEL_ECHO_AUTH_HOST=http://nginx:80

  react-frontend:
    container_name: mange_react
    build:
      dockerfile: Dockerfile
      context: "./fontend"
    ports:
      - "3000:3000"
    depends_on:
      - laravel-backend
    networks:
      - mange

volumes:
  mysql_data:
  backend_code:

networks:
  mange:
