name: Test React Cypress

on:
  pull_request:
    paths:
      - "fontend/**"
    branches: [main]
  workflow_call:

jobs:
  cypress-run:
    name: Cypress Run
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./fontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          working-directory: fontend
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 300
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload frontend coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend_coverage
          path: fontend/coverage/
